### ISSUE TITLE
application: suggested changes

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/training-curriculum#313]
## Part 1

- [x] Where do you find the item id from the link? I see it's in the actual URL, is it posted anywhere on the actual item link?

## Part 2

- [x] The link in 'lesson to download NWIS data' is broken.
- [x] The geojob took a while (I think ~10 min) -- maybe this was just a fluke? Or this amount of time is okay?

**Comment by lindsaycarr** [comment]
Discussed this with Jordan Walker and we decided the 10 minutes was OK. I added a note to this indicated that it would take about 10, just so people have an idea.

**Comment by lindsaycarr** [comment]
Closed by #316
